services:
  - type: web
    name: laravel-agenda
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
    # Garante persistência do banco SQLite
    mounts:
      - name: data
        path: /data
